sudo: required
services:
    - docker

before_install:
    - docker build -t alandandronic/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alandandronic/docker-react npm run test npm run test -- --coverage